### ISSUE TITLE
Broken TDL Abstraction

### ISSUE THREAD

**Issue by nightblade9** [nightblade9/furusiya#32]
The point of the `TdlAdapter` is to have one class to handle everything TDL-related; and one place to replace if we go with a different library.

We have a couple of broken abstractions:

- UI: `map_renderer` calls `blit` and operates directly on `ui_adapter.root`. `root` should be private and shouldn't be accessed; instead, we should call methods on `ui_adapter`.
- For input, we use `tdl.event.get` in several places. This should again be reflected into `ui_adapter.get_input` or some other method, it shouldn't access `tdl` directly

There are probably other broken abstractions we need to clean up.

**Comment by NegativeScript** [comment]
Fixed in #53.

**Comment by nightblade9** [comment]
👍
